/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup Status */
        get: operations["setup_status_api_v1_setup_get"];
        put?: never;
        /** Setup */
        post: operations["setup_api_v1_setup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_session_get"];
        put?: never;
        /** Login */
        post: operations["login_api_v1_session_post"];
        /** Logout */
        delete: operations["logout_api_v1_session_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/lab": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lab */
        get: operations["lab_api_v1_lab_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Provider Config */
        get: operations["get_provider_config_api_v1_ai_provider_get"];
        /** Save Provider Config */
        put: operations["save_provider_config_api_v1_ai_provider_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/provider/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Provider Models */
        get: operations["provider_models_api_v1_ai_provider_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/things": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Things */
        get: operations["list_things_api_v1_things_get"];
        put?: never;
        /** Add Thing */
        post: operations["add_thing_api_v1_things_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/things/{thing_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Thing */
        get: operations["get_thing_api_v1_things__thing_id__get"];
        put?: never;
        post?: never;
        /** Archive Thing */
        delete: operations["archive_thing_api_v1_things__thing_id__delete"];
        options?: never;
        head?: never;
        /** Patch Thing */
        patch: operations["patch_thing_api_v1_things__thing_id__patch"];
        trace?: never;
    };
    "/api/v1/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Locations */
        get: operations["list_locations_api_v1_locations_get"];
        put?: never;
        /** Add Location */
        post: operations["add_location_api_v1_locations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/code/{public_code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lookup Location */
        get: operations["lookup_location_api_v1_locations_code__public_code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/locations/{location_id}/qr.svg": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Location Qr */
        get: operations["location_qr_api_v1_locations__location_id__qr_svg_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/balances": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Balances */
        get: operations["balances_api_v1_inventory_balances_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/receive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Endpoint */
        post: operations["endpoint_api_v1_inventory_receive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Endpoint */
        post: operations["endpoint_api_v1_inventory_move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inventory/consume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Endpoint */
        post: operations["endpoint_api_v1_inventory_consume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Inbox */
        get: operations["list_inbox_api_v1_inbox_get"];
        put?: never;
        /** Capture Inbox */
        post: operations["capture_inbox_api_v1_inbox_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbox/{inbox_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Inbox Candidates */
        get: operations["list_inbox_candidates_api_v1_inbox__inbox_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_v1_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbox/{inbox_id}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Inbox Attachment */
        post: operations["upload_inbox_attachment_api_v1_inbox__inbox_id__attachments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbox/{inbox_id}/process": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Process Inbox */
        post: operations["process_inbox_api_v1_inbox__inbox_id__process_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbox/{inbox_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm Inbox */
        post: operations["confirm_inbox_api_v1_inbox__inbox_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_v1_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_v1_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Requirement */
        post: operations["add_requirement_api_v1_projects__project_id__requirements_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/allocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Allocate Project Stock */
        post: operations["allocate_project_stock_api_v1_projects__project_id__allocations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/allocations/{allocation_id}/recover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Recover Project Stock */
        post: operations["recover_project_stock_api_v1_projects__project_id__allocations__allocation_id__recover_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/things/{thing_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Fact */
        post: operations["add_fact_api_v1_things__thing_id__facts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/compatible": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compatible */
        post: operations["compatible_api_v1_knowledge_compatible_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Query */
        post: operations["ai_query_api_v1_ai_query_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AIAnswer */
        AIAnswer: {
            /**
             * Status
             * @enum {string}
             */
            status: "disabled" | "ready";
            /** Answer */
            answer: string;
            /** Evidence */
            evidence?: {
                [key: string]: unknown;
            }[];
        };
        /** AIQuery */
        AIQuery: {
            /** Query */
            query: string;
        };
        /** AllocationCreate */
        AllocationCreate: {
            /** Thing Id */
            thing_id: string;
            /** Location Id */
            location_id: string;
            /** Quantity */
            quantity: number | string;
            /**
             * State
             * @default reserved
             * @enum {string}
             */
            state: "reserved" | "in_use" | "recoverable";
        };
        /** AllocationOut */
        AllocationOut: {
            /** Id */
            id: string;
            /** Thing Id */
            thing_id: string;
            /** Location Id */
            location_id: string | null;
            /** Quantity */
            quantity: string;
            /** State */
            state: string;
        };
        /** AllocationRecover */
        AllocationRecover: {
            /** Location Id */
            location_id: string;
            /** Quantity */
            quantity: number | string;
        };
        /** BalanceOut */
        BalanceOut: {
            /** Thing Id */
            thing_id: string;
            /** Location Id */
            location_id: string;
            /** Quantity */
            quantity: string;
        };
        /** Body_upload_inbox_attachment_api_v1_inbox__inbox_id__attachments_post */
        Body_upload_inbox_attachment_api_v1_inbox__inbox_id__attachments_post: {
            /** Upload */
            upload: string;
        };
        /** CompatibilityRequest */
        CompatibilityRequest: {
            /** Required Capabilities */
            required_capabilities?: string[];
            /** Required Interfaces */
            required_interfaces?: string[];
            /** Minimum Facts */
            minimum_facts?: {
                [key: string]: number | string;
            };
        };
        /** CompatibilityResult */
        CompatibilityResult: {
            /** Thing Id */
            thing_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pass" | "fail" | "unknown";
            /** Evidence */
            evidence: string[];
        };
        /** FactCreate */
        FactCreate: {
            /** Key */
            key: string;
            /** Value Numeric */
            value_numeric?: number | string | null;
            /** Value Text */
            value_text?: string | null;
            /** Unit */
            unit?: string | null;
            /** Min Value */
            min_value?: number | string | null;
            /** Max Value */
            max_value?: number | string | null;
            /**
             * Source Type
             * @default user
             */
            source_type: string;
            /** Source Ref */
            source_ref?: string | null;
            /**
             * Verification State
             * @default unverified
             * @enum {string}
             */
            verification_state: "unverified" | "accepted" | "verified";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InboxCandidateInput */
        InboxCandidateInput: {
            /** Name */
            name: string;
            /** Quantity */
            quantity: number | string;
            /**
             * Category
             * @default uncategorized
             */
            category: string;
            /**
             * Confidence
             * @default unresolved
             * @enum {string}
             */
            confidence: "confirmed" | "likely" | "generic" | "unresolved";
        };
        /** InboxCandidateOut */
        InboxCandidateOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: string;
            /** Category */
            category: string;
            /** Confidence */
            confidence: string;
            /** Provenance */
            provenance: {
                [key: string]: unknown;
            };
        };
        /** InboxCapture */
        InboxCapture: {
            /**
             * Input Type
             * @enum {string}
             */
            input_type: "text" | "photo" | "screenshot" | "voice" | "pdf";
            /** Text */
            text?: string | null;
        };
        /** InboxConfirm */
        InboxConfirm: {
            /** Location Id */
            location_id: string;
            candidate: components["schemas"]["InboxCandidateInput"];
            /** Existing Thing Id */
            existing_thing_id?: string | null;
        };
        /** InboxOut */
        InboxOut: {
            /** Id */
            id: string;
            /** Input Type */
            input_type: string;
            /** Status */
            status: string;
            /** Text */
            text: string | null;
            /** Error */
            error: string | null;
            /** Processing Evidence */
            processing_evidence: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** LabOut */
        LabOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Units */
            units: string;
        };
        /** LocationCreate */
        LocationCreate: {
            /** Name */
            name: string;
            /** Parent Id */
            parent_id?: string | null;
        };
        /** LocationOut */
        LocationOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: string | null;
            /** Public Code */
            public_code: string;
            /** Revision */
            revision: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ProjectDetailOut */
        ProjectDetailOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Status */
            status: string;
            /** Requirements */
            requirements: components["schemas"]["RequirementOut"][];
            /** Allocations */
            allocations: components["schemas"]["AllocationOut"][];
        };
        /** ProjectOut */
        ProjectOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Status */
            status: string;
        };
        /**
         * ProviderConfigInput
         * @description OpenAI-compatible endpoint settings; an absent key preserves the stored key.
         */
        ProviderConfigInput: {
            /** Base Url */
            base_url: string;
            /** Model */
            model: string;
            /** Api Key */
            api_key?: string | null;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
        };
        /** ProviderConfigOut */
        ProviderConfigOut: {
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Base Url */
            base_url: string;
            /** Model */
            model: string;
            /** Enabled */
            enabled: boolean;
            /** Has Api Key */
            has_api_key: boolean;
            /**
             * Egress
             * @enum {string}
             */
            egress: "local" | "external";
        };
        /** ProviderModelsOut */
        ProviderModelsOut: {
            /** Models */
            models: string[];
            /**
             * Egress
             * @enum {string}
             */
            egress: "local" | "external";
        };
        /** RequirementCreate */
        RequirementCreate: {
            /** Name */
            name: string;
            /** Quantity */
            quantity: number | string;
            /**
             * Priority
             * @default required
             * @enum {string}
             */
            priority: "required" | "recommended" | "optional";
            /** Constraints */
            constraints?: {
                [key: string]: unknown;
            };
        };
        /** RequirementOut */
        RequirementOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Quantity */
            quantity: string;
            /** Priority */
            priority: string;
            /** Constraints */
            constraints: {
                [key: string]: unknown;
            };
        };
        /** SetupRequest */
        SetupRequest: {
            /** Token */
            token: string;
            /** Lab Name */
            lab_name: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
            /** Display Name */
            display_name: string;
        };
        /** StockMovementOut */
        StockMovementOut: {
            /** Id */
            id: string;
            /** Thing Id */
            thing_id: string;
            /** From Location Id */
            from_location_id: string | null;
            /** To Location Id */
            to_location_id: string | null;
            /** Quantity */
            quantity: string;
            /** Movement Type */
            movement_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** StockMutation */
        StockMutation: {
            /** Thing Id */
            thing_id: string;
            /** Quantity */
            quantity: number | string;
            /** To Location Id */
            to_location_id?: string | null;
            /** From Location Id */
            from_location_id?: string | null;
            /** Note */
            note?: string | null;
        };
        /** ThingCreate */
        ThingCreate: {
            /** Name */
            name: string;
            /**
             * Category
             * @default uncategorized
             */
            category: string;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Mpn */
            mpn?: string | null;
            /**
             * Tracking Mode
             * @default quantity
             * @constant
             */
            tracking_mode: "quantity";
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Aliases */
            aliases?: string[];
        };
        /** ThingOut */
        ThingOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Manufacturer */
            manufacturer: string | null;
            /** Mpn */
            mpn: string | null;
            /** Tracking Mode */
            tracking_mode: string;
            /** Metadata Json */
            metadata_json: {
                [key: string]: unknown;
            };
            /** Revision */
            revision: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** ThingPatch */
        ThingPatch: {
            /** Name */
            name?: string | null;
            /** Category */
            category?: string | null;
            /** Manufacturer */
            manufacturer?: string | null;
            /** Mpn */
            mpn?: string | null;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
            /** Revision */
            revision: number;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Is Owner */
            is_owner: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    setup_status_api_v1_setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean;
                    };
                };
            };
        };
    };
    setup_api_v1_setup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_session_delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lab_api_v1_lab_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LabOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_provider_config_api_v1_ai_provider_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderConfigOut"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_provider_config_api_v1_ai_provider_put: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderConfigInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderConfigOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    provider_models_api_v1_ai_provider_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderModelsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_things_api_v1_things_get: {
        parameters: {
            query?: {
                q?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_thing_api_v1_things_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThingCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_thing_api_v1_things__thing_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                thing_id: string;
            };
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_thing_api_v1_things__thing_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                thing_id: string;
            };
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_thing_api_v1_things__thing_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                thing_id: string;
            };
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ThingPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_locations_api_v1_locations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_location_api_v1_locations_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_location_api_v1_locations_code__public_code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                public_code: string;
            };
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LocationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    location_qr_api_v1_locations__location_id__qr_svg_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                location_id: string;
            };
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    balances_api_v1_inventory_balances_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BalanceOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoint_api_v1_inventory_receive_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockMutation"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoint_api_v1_inventory_move_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockMutation"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    endpoint_api_v1_inventory_consume_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockMutation"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_inbox_api_v1_inbox_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    capture_inbox_api_v1_inbox_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxCapture"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_inbox_candidates_api_v1_inbox__inbox_id__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inbox_id: string;
            };
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxCandidateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_v1_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_inbox_attachment_api_v1_inbox__inbox_id__attachments_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                inbox_id: string;
            };
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_inbox_attachment_api_v1_inbox__inbox_id__attachments_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    process_inbox_api_v1_inbox__inbox_id__process_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                inbox_id: string;
            };
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_inbox_api_v1_inbox__inbox_id__confirm_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                inbox_id: string;
            };
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InboxConfirm"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_api_v1_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_v1_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_requirement_api_v1_projects__project_id__requirements_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequirementCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    allocate_project_stock_api_v1_projects__project_id__allocations_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recover_project_stock_api_v1_projects__project_id__allocations__allocation_id__recover_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
                "Idempotency-Key"?: string | null;
            };
            path: {
                project_id: string;
                allocation_id: string;
            };
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AllocationRecover"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMovementOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_fact_api_v1_things__thing_id__facts_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                thing_id: string;
            };
            cookie?: {
                openlab_csrf?: string | null;
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compatible_api_v1_knowledge_compatible_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompatibilityRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompatibilityResult"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_query_api_v1_ai_query_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                openlab_session?: string | null;
            };
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AIQuery"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AIAnswer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
